server.port=8091

spring.application.name=tutoring-center

spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.username=postgres
spring.datasource.password=conthino

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.cors.allowed-origins=http://localhost:3000,https://yourfrontend.com

app.jwt.secret=58731eac2d0c5861e084a09c519becc17e5e3c33b5c06434b5e50cabe06a1fe3cf46ea6ad9c9084b8160a551538169059bc19947aae71db775135275500a92c09d3445e74416e08dd2dc1e8d4025d745a74403a0a2c674228b347580ca38fbb025a1466787f7d2784e4cd357806019431ae6b930df0c210c268b4ef74ebeed85
app.jwt.accessToken.expirationMs=900000
app.jwt.refreshToken.expirationMs=86400000
app.jwt.issuer=auth-service
