spring.application.name=tutoring-center

spring.datasource.url=jdbc:postgresql://localhost:5432/tutoring_center
spring.datasource.username=postgres
spring.datasource.password=conthino

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
