spring.application.name=tutoring-center

spring.datasource.url=jdbc:postgresql://188.166.233.115:5432/tutoring-center
spring.datasource.username=phuchh0209
spring.datasource.password=conthino

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
